spring:
  config:
    additional-location: classpath:/oauth2/
  profiles:
    active: oauth2
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    async:
      request-timeout: 3000000

logging:
  level:
    org.hibernate.type.descriptor.sql: debug

server:
  error:
    include-exception: true
    include-stacktrace: always
  port: 8080

springdoc:
  swagger-ui:
    path: /api/v1/docs
    url: /openapi.json
  api-docs:
    path: /api/v1/api-docs
